services:
  django: &django
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: provider.local
    networks:
      - my_network
    volumes:
      - ./:/app/
      - ./.env:/app/.env
    ports:
      - 8000:8000
    env_file:
      - ./.env
    command: /start

networks:
  my_network:
    external: true
